[package]
edition = "2018"
name = "quickjs"
version = "0.1.0-alpha.1"
readme = "README.md"
documentation = "https://docs.rs/quickjs"
repository = "https://github.com/theduke/quickjs-rs"
license = "MIT"
authors = ["Christoph Herzog <chris@theduke.at>"]

[dependencies]
quickjs-sys = { version = "0.1.0-alpha.1", path = "./quickjs-sys" }

[workspace]
members = [
    "quickjs-sys",
]
