[package]
edition = "2018"
name = "quick"
description = "QuickJS Javascript engine wrapper"
version = "0.1.0-alpha.4"
readme = "README.md"
documentation = "https://docs.rs/quickjs"
repository = "https://github.com/theduke/quickjs-rs"
license = "MIT"
authors = ["Christoph Herzog <chris@theduke.at>"]
keywords = ["quickjs", "javascript", "js", "engine", "interpreter"]

[dependencies]
libquickjs-sys = { version = "0.1.0-alpha.2", path = "./libquickjs-sys" }

[workspace]
members = [
    "libquickjs-sys",
]
